version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgre
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - db_net

  webapp:
    restart: always
    container_name: webapp
    build: ./
    volumes:
      - ./:/app
      - ./static:/app/static
      - ./media:/app/media
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    networks:
      - db_net

  nginx:
    build: ./docker/nginx
    container_name: developer_nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - webapp
    networks:
      - db_net

volumes:
  postgres_data:

networks:
  db_net: