version: '3.9'

services:
  web:
    build: .
    command: >
          sh -c "python manage.py makemigrations &&
          python manage.py migrate
          && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - .:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data/
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    env_file:
      - .env
    hostname: db

volumes:
  postgres_data: