# Generated by Django 4.2.1 on 2024-09-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=125, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='developer',
            name='sub_lesson',
            field=models.ManyToManyField(blank=True, related_name='sub', to='developer.subdeveloper'),
        ),
    ]
