# Generated by Django 4.2.1 on 2024-09-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_subcategoryoop_alter_categoryoop_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['time_create'], 'verbose_name': 'Python', 'verbose_name_plural': 'Python'},
        ),
        migrations.AlterModelOptions(
            name='subcategoryoop',
            options={'verbose_name': 'ООП подтема', 'verbose_name_plural': 'ООП подтемы'},
        ),
        migrations.AlterModelOptions(
            name='subdeveloper',
            options={'verbose_name': 'Python подтема', 'verbose_name_plural': 'Python подтемы'},
        ),
        migrations.AlterField(
            model_name='categoryoop',
            name='content',
            field=models.TextField(blank=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='categoryoop',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='categoryoop',
            name='lesson',
            field=models.CharField(max_length=100, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='categoryoop',
            name='slug',
            field=models.SlugField(max_length=125, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='categoryoop',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='categoryoop',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
