# Generated by Django 4.2.1 on 2024-10-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_alter_developer_options_alter_subcategoryoop_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryAlgoritm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=100, verbose_name='Подтема')),
                ('content', models.TextField(blank=True, verbose_name='Информация')),
                ('slug', models.SlugField(max_length=125, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Алгоритмы подтема',
                'verbose_name_plural': 'Алгоритмы подтемы',
            },
        ),
        migrations.CreateModel(
            name='CategoryAlgoritm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=100, verbose_name='Тема')),
                ('content', models.TextField(blank=True, verbose_name='Информация')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Статус')),
                ('slug', models.SlugField(max_length=125, unique=True, verbose_name='Слаг')),
                ('sub_lesson_algoritm', models.ManyToManyField(blank=True, related_name='sub_algoritm', to='developer.subcategoryalgoritm')),
            ],
            options={
                'verbose_name': 'Алгоритмы',
                'verbose_name_plural': 'Алгоритмы',
            },
        ),
    ]
